rank=$1

# path to log file. clips that have been successfully processed or errors will be record in the log file
# recommended value: video2clip.data
LOGFILE="/mnt/shuang/Data/ego4d/preprocessed_data/video2clip_$rank.data"

# path to processed videos
# e.g. on vm: /home/COMPASS-user/workspace/blobfuse/shuang/Data/ego4d/preprocessed_data/egoclip
SOURCE="/mnt/shuang/Data/ego4d/preprocessed_data/egoclip"

# path to log file generated by extract_frame.sh
# e.g. processed_video.data
PROCESSED_VIDEO_FILE="/mnt/shuang/Data/ego4d/preprocessed_data/processed_video_$rank.data"
EXCLUDE="/mnt/shuang/Data/ego4d/preprocessed_data/exclude_list_$rank.data"
# path to egoclip annotation file 
# e.g. on vm: /home/COMPASS-user/workspace/blobfuse/shuang/Data/ego4d/data/v1/annotations/egoclip.csv
OLD_ANNOTATION_FILE="/mnt/shuang/Data/ego4d/data/v1/annotations/egoclip.csv"

# path to save new egoclip annotation file (contains more information including start frame, etc.)
# e.g. on vm: /home/COMPASS-user/workspace/blobfuse/shuang/Data/ego4d/data/v1/annotations/new_egoclip.csv
NEW_ANNOTATION_FILE="/mnt/shuang/Data/ego4d/preprocessed_data/egoclip_$rank.csv"

# maximum number of threads that this process is allowed to own
MAX_NUM_THREADS=64

python video2clip.py \
    --source $SOURCE \
    --logfile $LOGFILE \
    --processed_video_file $PROCESSED_VIDEO_FILE \
    --old_anno_path $OLD_ANNOTATION_FILE \
    --new_anno_path $NEW_ANNOTATION_FILE \
    --max_thread_num $MAX_NUM_THREADS \
    --exclude $EXCLUDE