cfg:
  - DATA: 
    # Data Loading
    - ANN_DIR: ,
    - VIDEO_DIR_PATH: ,
    - CLIPS_SAVE_PATH: , # "/mnt/shuang/Data/ego4d/preprocessed_data/pos"
    - NO_SC_PATH: , # "/mnt/shuang/Data/ego4d/preprocessed_data/neg"

    - SAVE_AS_ZIP: ,                # save frames in zip file for efficient data loading
    - READ_BY_CLIPS: ,        # read by clips or full_scale video

    # Data Sampling
    - CLIP_LEN_SEC: ,      # Duration time in second of clip
    - CROP_SIZE: ,
    - SAMPLING_FPS: , # Sampled frames per second for training