batch_size: 12
epochs: 100
update_freq: 1
save_ckpt_freq: 10

# Model parameters
model: 'oscc_vit_base_patch16_224'
tubelet_size: 2
input_size: 224

drop: 0.0
attn_drop_rate: 0.0
drop_path: 0.1

disable_eval_during_finetuning: false

# Optimizer parameters
opt: 'adamw'
opt_eps: 1.0e-8
opt_betas: [0.9, 0.999]
clip_grad: null
momentum: 0.9
weight_decay: 0.05
weight_decay_end: null

lr: 5.0e-4
layer_decay: 0.75
warmup_lr: 1.0e-6
min_lr: 1.0e-6

warmup_epochs: 5
warmup_steps: -1

# Augmentation parameters
# color_jitter: 0.4
# aa: 'rand-m7-n4-mstd0.5-inc1'
smoothing: 0.1
# train_interpolation: 'bicubic'

# Evaluation parameters
# crop_pct: null
# short_side_size: 224
# test_num_segment: 5
# test_num_crop: 3

# Random Erase params
# reprob: 0.25
# remode: 'pixel'
# recount: 1
# resplit: false

# Mixup params
mixup: 0.8
cutmix: 1.0
cutmix_minmax: null
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: 'batch'

# Finetuning params
finetune: '/data/jiachen/ssvl_output/ts_preepic55_A33/checkpoint-599.pth'
model_key: 'model|module'
model_prefix: ''
init_scale: 0.001
use_mean_pooling: true # if false, then use cls

# clip_len: 8

# Dataset parameters
# eval_data_path: null
# nb_classes: -1
# imagenet_default_mean_and_std: true
# num_segments: 1
# num_frames: 16
# sampling_rate: 4

output_dir: /data/shared/output/jiachen/ssvl 
log_dir: /data/shared/output/jiachen/ssvl 
# seed: 0
resume: ''
auto_resume: true

save_ckpt: true
start_epoch: 0
num_workers: 20

cfg:

  # Data Loading
  ANN_DIR: "/data/shared/ssvl/ego4d/v1/annotations"
  VIDEO_DIR_PATH: "/data/shared/ssvl/ego4d/v1/full_scale"
  CLIPS_SAVE_PATH: "/data/shared/ssvl/ego4d/v1/fho_oscc/pos"  # "/mnt/shuang/Data/ego4d/preprocessed_data/pos"
  NO_SC_PATH: "/data/shared/ssvl/ego4d/v1/fho_oscc/neg"        # "/mnt/shuang/Data/ego4d/preprocessed_data/neg"

  SAVE_AS_ZIP: True                # save frames in zip file for efficient data loading
  CLIP_LEN_SEC: 8                  # Duration time in second of clip
  SAMPLING_FPS: 2                  # Sampled frames per second for training
  NUM_FRAMES: 16

  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  # "FRAME_FORMAT": "{:10d}.jpeg",

  short_side_size: 256
  input_size: 224
  # train
  repeat_sample: 1
  # train augmentation
  auto_augment: 'rand-m7-n4-mstd0.5-inc1'
  rand_erase_count: 1
  rand_erase_prob: 0.25
  rand_erase_mode: "pixel"
  train_interpolation: "bicubic"
  # test
  test_spatial_sample: 3

  task: "oscc"
  load_flow: "none" # [online, local, none] 