# configuration for pretraining
# configurations needed in pretraining

batch_size: 1
epochs: 300
save_ckpt_freq: 10

# Model parameters
model: "pretrain_videomae_multimodal_base_patch16_224"
decoder_depth: 6


# possible values for 'mask_type': [multimodal, agnostic, tube, agnostic_tube, tube_agnostic, agnostic_agnostic, tube_tube]
# Notice:
# when input modality is composed of rgb and flow and mask_type is either 'agnostic' or 'tube' 
# then perform uniform sampling among all rgb and flow tokens instead of independently amoung each modality
mask_type: "multimodal"

# possible values for 'mask_ratio': float or str of format "float_float"
# float_float is used to specify different masking ratio for each modality
# only works when rgb and flow are both input modality
# Notice:
# mask_ratio should correspond with mask_type that when mask_type is in [agnostic, tube], then mask ratio is a float
# else mask_ratio should be str of format 'float_float'
mask_ratio: 0.9

modality: "rgbflow"
input_size: 224
drop_path: 0.0
normlize_target: False

# Optimizer parameters
opt: "adamw"
opt_eps: 1.0e-8
opt_betas: null
clip_grad: null
momentum: 0.9
weight_decay: 0.0001
weight_decay_end: null

lr: 5.0e-5
warmup_lr: 1.0e-7
min_lr: 1.0e-7

warmup_epochs: 20
warmup_steps: -1

# Dataset parameters
data_path: '/path/to/list_kinetics-400'
imagenet_default_mean_and_std: true
num_frames: 16
sampling_rate: 4
output_dir: "/data/jiachen/output/multimodal"
log_dir: "/data/jiachen/output/multimodal"

resume: ""
auto_resume: False

start_epoch: 0
num_workers: 30
pin_mem: true

pretrain: "multimodal"

lamb: [1, 1, 1, 1]

# ckpt: ""

# configurations for epic-kitchens dataset
cfg:
  task: "epic-kitchens"
  EPICKITCHENS:
    VISUAL_DATA_DIR: "/data/shared/ssvl/epic-kitchens55/3h91syskeag572hl6tvuovwv4d/frames_rgb_flow"
    ANNOTATIONS_DIR: "/data/shared/ssvl/epic-kitchens55/3h91syskeag572hl6tvuovwv4d/annotations"
    TRAIN_LIST: "EPIC_train_action_labels.pkl"
    VAL_LIST: ""
    TEST_LIST: ""

  DATA:
    # do not need in pretrain
    # - MEAN: ""
    # - STD: ""
    SAMPLING_RATE: 2
    NUM_FRAMES: 16
    REPEATED_SAMPLING: 0
    READ_FROM_TAR: false

  VERSION: 55
  ONINE_EXTRACTING: true
