batch_size: 6
epochs: 100
update_freq: 1
save_ckpt_freq: 10

# Model parameters
model: 'vit_lta_base_patch16_224'
tubelet_size: 2
input_size: 224

drop: 0.0
attn_drop_rate: 0.0
drop_path: 0.1

disable_eval_during_finetuning: false

# Optimizer parameters
opt: 'adamw'
opt_eps: 1.0e-8
opt_betas: [0.9, 0.999]
clip_grad: null
momentum: 0.9
weight_decay: 0.05
weight_decay_end: null

lr: 5.0e-5

layer_decay: 0.75
warmup_lr: 1.0e-7
min_lr: 1.0e-7

warmup_epochs: 5
warmup_steps: -1

# Mixup params

gamma: 8
mixup: 0.0
cutmix: 0.0
cutmix_minmax: null
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: 'batch'

# Finetuning params
finetune: '/mnt/shuang/Output/output_ego4d/multimodal_preegoclip_A1/checkpoint-9.pth'
model_key: 'model|module'
model_prefix: ''
init_scale: 0.001
use_mean_pooling: true # if false, then use cls

head_type: baseline

output_dir: /mnt/shuang/Output/output_ego4d/
log_dir: /mnt/shuang/Output/output_ego4d/
# seed: 0
resume: ''
auto_resume: false
# flow_mode: ""
save_ckpt: false
start_epoch: 0
num_workers: 20

cfg:
  # Data Loading
  ANN_DIR: "/mnt/shuang/Data/ego4d/data/v1/annotations"
  FRAME_DIR_PATH: "/mnt/shuang/Data/ego4d/preprocessed_data/fho_lta"
  NUM_FRAMES: 16 # number of frames sampled from each input clip

  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]

  FRAME_FORMAT: "{:010d}.jpg"  # image frame format

  repeat_sample: 1
  input_clip_num: 1 # number of input clips
  num_action_predict: 20
  short_side_size: 256
  input_size: 224

  test_spatial_crop_num: 3
  test_temporal_crop_num: 1

  task: "lta_noun"
  load_flow: "none"