DATA:
  VIDEO_DIR_PATH: /mnt/shared/ssvl/ego4d/v1/clips
  ANN_PATH: /mnt/shared/ssvl/ego4d/v1/annotations
  SPLIT_PATH: /home/sid/canonical_dataset/2021-08-09_provided_splits
  CLIPS_SAVE_PATH: /mnt/shared/ssvl/ego4d/v1/pos
  NO_SC_PATH: /mnt/shared/ssvl/ego4d/v1/neg
  NO_SC_SPLIT_PATH: /mnt/traffic/home/zhongjieming/Ego4DBaseline/canonical_dataset/negative_clips_splits_json_2021-09-17.json
  SAMPLING_FPS: 2
  CLIP_LEN_SEC: 8
  CROP_SIZE: 225
  TASK: "state_change_detection_and_keyframe_localization"
  READ_BY_CLIPS: False
TRAIN:
  TRAIN_ENABLE: True
  DATASET: StateChangeDetectionAndKeyframeLocalisation
  BATCH_SIZE: 8
TEST:
  ENABLE: False
  BATCH_SIZE: 8
  JSON: /home/sid/canonical_dataset/fixed_test_set_canonical_17-09-21.json
  VAL_JSON: /home/sid/canonical_dataset/fixed_val_set_canonical_17-09-21.json
  DATASET: StateChangeDetectionAndKeyframeLocalisation
DATA_LOADER:
  NUM_WORKERS: 32
  PIN_MEMORY: True
  SHUFFLE: True
  IS_NO_STATE_CHANGE: True
MISC:
  FAST_DEV_RUN: False
  NUM_GPUS: 1
  # lightning_logs outputs dir
  OUTPUT_DIR: /mnt/traffic/home/zhongjieming
  # CHECKPOINT_FILE_PATH: /mnt/traffic/home/zhongjieming/lightning_logs/version_23/checkpoints/epoch=34-step=7800.ckpt
  ENABLE_LOGGING: True
MODEL:
  ARCH: "slow_layer5"
  NUM_CLASSES: [1]
  NUM_STATE_CLASSES: [2]
  HEAD_ACT: softmax
  MODEL_NAME: DualHeadResNet
SOLVER:
  BASE_LR: 0.0001
  MAX_EPOCH: 100
  # ACCELERATOR: 'dp'
